### PR TITLE
Add Python 3 support 

### PR DESCRIPTION
**Pull request by Digenis**
Continued from #28

Users who want to test it can install it with:
 `pip install git+https://github.com/scrapy/scrapyd-client.git@python3-wip`

### CODE REVIEW

**Comment by UberMeatShield** [comment]
This would be really great to get into the released code!   The pyhon3 support works but without the deploy it makes for an interesting lifecycle 👍

**Comment by Digenis** [comment]
@UberMeatShield, what do you mean "without the deploy"?
Did you mean "without a release in pypi"?

**Comment by UberMeatShield** [comment]
@Digenis scrapyd-deploy doesn't work without further python3 modifications, I had started doing this same change but then another member of my team found this MR.    Thanks for beating me to it :)

**Comment by LISTERINE** [comment]
Any news on the status of this PR? It would be really great to have this merged into the main project.

**Comment by redapple** [comment]
@Digenis , maybe we can release an alpha release with this Python 3 changes and see how it goes.

**Comment by Digenis** [comment]
I prepared a branch merging master and python3-wip.
@LISTERINE you can install it with
`pip install 'git+https://github.com/scrapy/scrapyd-client.git@1.1.0dev'`
Any feedback is welcome.

**Comment by LISTERINE** [comment]
Terrific, thanks!

**Comment by medse** [comment]
Hi all!

Haven't seen there's python3 work underway, so did it for myself today. Works for me. I've changed to requests and logging. I'm not very good in git, so cannot do fancy things like branches and merge requests (anyway, they won't be pulled for another year as I see).
It's based on master and needs attention from one of the seasoned scrapyd users (I just don't know what Exceptions to watch for and what urls there may be). So if somebody needs the code, just have it. Can participate and help if you need.
[scrapyd-deploy.zip](https://github.com/scrapy/scrapyd-client/files/679064/scrapyd-deploy.zip)

**Comment by Digenis** [comment]
Hi, @medse

Thank you for your patch.

This is hard to review as a patch that introduces python3 support
because it has changes that should have been in separate patches
and changes that seem irrelevant (at first glance at least) to python3 support.

We will continue with the current work on the python3 port.
If you want to help more, you can try the dev branch and give feedback,
see [my comment above](https://github.com/scrapy/scrapyd-client/pull/29#issuecomment-265731621)

**Comment by medse** [comment]
@Digenis, yes, I've also switched to requests to cut the code. Don't see why you stick to pure urllib. Well, not my problem if you don't need it. I'm happy to use it myself:)

**Comment by UberMeatShield** [comment]
Our testing of the scrapyd-python 3 branch git+https://github.com/scrapy/scrapyd-client.git@1.1.0dev seemed to have everything working ok!   If it merges that would be great :)

**Pull request merged**
