### PR TITLE
Fix ScrapyDeprecationWarning when calling scrapy.utils.python.retry_on_eintr 

### LINKED ISSUE #69: Error trying to deploy
```
Packing version 1606931479
/usr/local/bin/scrapyd-deploy:259: ScrapyDeprecationWarning: Call to deprecated function retry_on_eintr.
  retry_on_eintr(check_call, [sys.executable, 'setup.py', 'clean', '-a', 'bdist_egg', '-d', d], stdout=o, stderr=e)
Deploying to project "platziScraper" in http://localhost:6800/addversion.json
Deploy failed: <urlopen error [Errno 111] Connection refused>
```

### PR DESCRIPTION
**Pull request by mxdev88**
This PR fixes ScrapyDeprecationWarning and applies suggested fix from scrapy/scrapy#4683.
It will avoid breaking the code when it is indeed removed from scrapy code base.

closes #69

### CODE REVIEW

**Comment by ava7** [comment]
@mxdev88 There is a missing import of `errno` package. [original source](https://github.com/scrapy/scrapy/blob/a6b36bf8ad5cd4760f50392dd9c9a91b8af69541/scrapy/utils/python.py#L4)

**Comment by mxdev88** [comment]
> 
> 
> @mxdev88 There is a missing import of `errno` package. [original source](https://github.com/scrapy/scrapy/blob/a6b36bf8ad5cd4760f50392dd9c9a91b8af69541/scrapy/utils/python.py#L4)

**Comment by mxdev88** [comment]
I've fixed this. thanks for raising @ava7

**Review by AlaaKanaan — APPROVED** [review]

**Review by jpmckinney — APPROVED** [review]

**Comment by jpmckinney** [comment]
Thanks!

**Pull request merged**
