### PR TITLE
cli with subcommands

### PR DESCRIPTION
**Pull request by funkyfuture**
okay, here's a proposal to solve #36. this implements a `scrapyd-client` command with these subcommands for now:

- `deploy` (delegates to `scrapyd-deploy`)
- `projects`
- `schedule`
- `spiders`

one thing is bugging me: while `projects` and `schedule` output one result per line (a project's name resp. a job id) which can easily be consumed in shell scripts, the `spiders` command's output is rather human-oriented:

    <project_0>
      <spider_0>
      <spider_n>
    <project_n>
      <spider_0>
      <spider_n>

there could be an option to format more robot-friendly:

    <project_0>:<spider_0>,…
    <project_1>:<spider_0>,…
    …

but which would be the default?

i will will amend tests, inline and user docs when the concept is approved.

ths pr sits on top of #35.

### CODE REVIEW

**Comment by funkyfuture** [comment]
remind me: set a proper user-agent

**Comment by funkyfuture** [comment]
@redapple have you had the opportunity to have a look on this?

**Comment by redapple** [comment]
Hey @funkyfuture , I think it's a great addition! Thank you for this.
Could `cli.py` be split into a module for commands and one for the CLI itself? (I see comments seperating sections in the file)
Also, have you had a chance to add some tests for these new commands?

**Comment by redapple** [comment]
I'm not sure there's a need for a "more robot-friendly" format for listing spiders. The CLI is afterall intended for humans on the command line.

**Comment by funkyfuture** [comment]
okay, i amended all the missing stuff.

> I'm not sure there's a need for a "more robot-friendly" format for listing spiders. The CLI is afterall intended for humans on the command line.

i often find myself scripting and am very happy about any tool whose output i can easily parse. i added this as  `-v` / `--verbose` option.

1f793be0b45882a781a0c8fd28071de4e56c92f7 introduces a significant design change where projects and spiders are passed as positional arguments, the reasoning is a less verbose syntax. imo this should also be applied later when `scrapyd-client deploy` gets a native implementation.

**Comment by redapple** [comment]
Hey @funkyfuture , I've started playing with this just now.
A couple of comments for now:

- would it be possible to make project and spider mandatory for `scrapyd-client schedule`?
I typed that and I got all spiders of the [testspiders](https://github.com/scrapinghub/testspiders) project running.
(I'm not sure why I got all the same 
Or at least make `* *`  allowed but explicit?

- when all these jobs started running, I was actually looking for a `scrapyd-client cancel <jobid>` (and probably a `scrapyd-client listjobs)`.
do you think it'd be hard to get it implemented? It can be another PR of course.

Again, a huge thank you for starting this!

**Comment by funkyfuture** [comment]
regarding the spiders, yes that's just changing the argument parser. i will push that within the next hours.

concerning the other commands, i'd like not to include these here. but i hope that it will be easy to amend these once the general design is approved.

**Comment by redapple** [comment]
Alright, lets work on other commands in another iteration outside of this PR.

**Comment by funkyfuture** [comment]
okay, i removed any `*` default.

**Comment by redapple** [comment]
Thank you @funkyfuture

**Comment by redapple** [comment]
Hey @funkyfuture , I've (finally) released a version with you new CLI.
It's an alpha release still, but it's out there: [1.2.0a1](https://pypi.python.org/pypi/scrapyd-client/1.2.0a1)
Thanks again!

**Pull request merged**
