### PR TITLE
Improvements for the autogenerated setup.py files

### PR DESCRIPTION
**Pull request by mineo**
This pull request makes the autogenerated setup.py file include the name
of the project and its current version instead of the generic 'project'
at version '1.0'.

### CODE REVIEW

**Comment by pablohoffman** [comment]
the change looks good, but i'm just wondering where you need this, since the name and version of the deployed is meant go be opaque to everything else other than scrapyd.

**Comment by mineo** [comment]
To be honest, I'm not yet sure!:-) I just started playing with scrapy earlier today (and already have code that works, yay) and want to later that into an already existing Twisted application (I'm not sure yet how to do that, but we'll see), so ideally I'd just declare a dependency for that, which means my scrapy code needs to be installable by pip and for that I need a setup.py.

**Comment by jayzeng** [comment]
Ah, interesting idea @mineo . Can you resolve the merge conflict and I will merge it in.

**Comment by mineo** [comment]
@jayzeng I've merged master into this branch and hopefully resolved all the conflicts. Deploying via -a or without it worked here.

However, https://github.com/scrapy/scrapyd-client/commit/3f815dddb00d0b9ed4f251fa07dcbab740b66f74 looks like a very wrong commit: all the important values set by `_build_egg_and_deploy_target` (in particular `tmpdir` and `exitcode` which are both used in `main`) do not get returned, which means temporary directories will not get cleaned up and the exitcode will always be 0 if `-a` is used.

**Comment by mineo** [comment]
Ping.

**Comment by mineo** [comment]
Ping.

**Comment by Digenis** [comment]
@mineo, gonna look into it tomorrow

**Comment by Digenis** [comment]
@mineo, you are right about 3f815dd, it should be patched.

I don't see why you need the version included in `setup.py`.
It is generated just once, so even if you build a newer version
only scrapyd will know about it and not even in a package-version sense.
Maybe you would want an abstract setup.py that gets the version on its own.
scrapy-client will not help you updating setup.py, nor do I think it should touch it if it exists.

For the rest, I comment on the diffs.

**Comment by mineo** [comment]
@Digenis As I said in an earlier comment, I've added a setup.py to an already existing spider to add it as a dependency in another project, so I wanted a proper version number. A version was generated or I specified one, therefore just writing it to the setup.py file made sense.

**Comment by Digenis** [comment]
So you want to package a scrapy project.
scrapyd and scrapyd-client are not concerned at all with packaging.
scrapyd-client only eggifies the project to send it to scrapyd.
The project version scrapyd cares about
is just a query argument in the post request to addversion.json.
This is different from the package version inside the egg;
scrapyd ignores the internal version.

The generated setup.py is a dummy config for packaging purposes,
not for real packaging.
Perhaps scrapyd-deploy shouldn't ever write a setup.py.

There is no connection between the project name and version in setup.py
with the deployed project name and version.
What your patch does is hardcoding the project name from scrapy.cfg
and the version it had in the fist deployment.

I don't think it's in the scope of scrapyd-client to create templates for packaging.
It won't get in your way if you try to package because it won't touch an existing setup.py.

In the current state of this PR, you will still have to manually edit setup.py
not only in case of renaming your package
but also every time you want to bump your _package_ version.

However there are useful ideas here that we could discuss.
There are possible improvements that on the same time can solve your problem
like enabling the default setup.py to read the project name from scrapy.cfg
instead of using a dummy name
and leaving it up to setup.py to generate the version
using the versioning scheme configured in scrapy.cfg.

Currently, the generated setup.py hardcodes the settings module during the first deployment.
I consider this a bug because users may edit scrapy.cfg and rename folders
but the reference to the old settings module will remain there.
This PR goes in the direction of this bug, hardcoding more things in setup.py
(even if scrapyd and scrapyd-client ignore them in this case).
I want to see something in the opposite direction, creating a more dynamic setup.py.

**Pull request closed without merging**
