### PR TITLE
If you have configured more than one target to deploy scrapy project,…

### PR DESCRIPTION
**Pull request by mariotux**
… now you can deploy all targets with one command using scrapyd-deploy -a

### CODE REVIEW

**Comment by Digenis** [comment]
Keeping you commit messages to 50 characters or less greatly improves readability.
What is your use case for deploying to multiple targets?

**Comment by mariotux** [comment]
I deploy in multiple targets for distributed web scraping task. I've a main application who manage a pool of scrapyd servers.

**Comment by Digenis** [comment]
After the discussions on the diffs, the rebases and testing it myself.
I think it's ok to merge. 

Maintainers?

**Comment by pablohoffman** [comment]
I am OK with this.

@jayzeng still interested in the scrapyd maintenance?

**Comment by jayzeng** [comment]
Yeah, tied with work (just launched the product), but I still would love to help.

**Comment by jayzeng** [comment]
@mariotux LGTM

**Comment by pablohoffman** [comment]
Awesome, can you merge @jayzeng?

**Comment by Digenis** [comment]
thank you

**Pull request merged**
