### PR TITLE
Passing pep8 on all the python files

### PR DESCRIPTION
**Pull request by david-caro**
Signed-off-by: David Caro david@dcaro.es

### CODE REVIEW

**Comment by Digenis** [comment]
I think what mostly downgrades the quality of the code is not the style
but the organization. Everything is dropped in a single file.
4d50286 doesn't seem to add a lot of history noise on lines that have actual code
so I think it's ok to merge it.

But first you need to fix your branching,
96b72c4 and def197c are from another branch.
Branch from master instead.

**Comment by david-caro** [comment]
Yes, sorry. This patch is mostly to keep my editor from complaining on the pep8 stuff, not really changing the quality of the code yep.

**Comment by david-caro** [comment]
ping?

**Comment by funkyfuture** [comment]
this would also be solved with #37.

**Comment by daviscabral** [comment]
Please keep going with this, this would make life of people wanting to contribute easier. :+1:

**Comment by jpmckinney** [comment]
The project runs `flake8` in CI, so I believe this has since been resolved.

**Pull request closed without merging**
